### ISSUE TITLE
Try if originalDate can be extracted from video files

### ISSUE THREAD

**Issue by ottlinger** [ottlinger/fotorenamer#31]
Files such as MTS / AVCHD contain EXIF information as well - verify if that is enough to be of use with the fotorenamer tool.

**Comment by ottlinger** [comment]
Seems not to work, just adding MTS yields stacktraces:
```
2016-03-28 21:45:31,499 ERROR d.a.f.i.CreationDateFromExifImageRenamer [Thread-8] Error during exif date extraction: 
org.apache.commons.imaging.ImageReadException: Can't parse this format.
        at org.apache.commons.imaging.Imaging.getImageParser(Imaging.java:761) ~[commons-imaging-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.commons.imaging.Imaging.getMetadata(Imaging.java:1114) ~[commons-imaging-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.commons.imaging.Imaging.getMetadata(Imaging.java:1109) ~[commons-imaging-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.apache.commons.imaging.Imaging.getMetadata(Imaging.java:1084) ~[commons-imaging-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at de.aikiit.fotorenamer.image.MetaDataExtractor.getExifMetadata(MetaDataExtractor.java:95) ~[classes/:?]
        at de.aikiit.fotorenamer.image.MetaDataExtractor.generateCreationDateInCorrectFormat(MetaDataExtractor.java:147) ~[classes/:?]
        at de.aikiit.fotorenamer.image.CreationDateFromExifImageRenamer.renameImage(CreationDateFromExifImageRenamer.java:77) ~[classes/:?]
        at de.aikiit.fotorenamer.image.AbstractImageRenamer.lambda$renameFiles$0(AbstractImageRenamer.java:114) ~[classes/:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_77]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) [?:1.8.0_77]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_77]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:1.8.0_77]
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_77]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_77]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_77]
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401) [?:1.8.0_77]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) [?:1.8.0_77]
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) [?:1.8.0_77]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) [?:1.8.0_77]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) [?:1.8.0_77]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) [?:1.8.0_77]
        at de.aikiit.fotorenamer.image.AbstractImageRenamer.renameFiles(AbstractImageRenamer.java:140) [classes/:?]
        at de.aikiit.fotorenamer.image.AbstractImageRenamer.run(AbstractImageRenamer.java:165) [classes/:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
```

**Comment by ottlinger** [comment]
Not working as hoped for :-(
